---
title: "Description of assessment model"
author: "by Quang C. Huynh <q.huynh@oceans.ubc.ca>"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette: 
    toc: true
    number_sections: true
vignette: >
  %\VignetteIndexEntry{Description of assessment model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { equationNumbers: {autoNumber: "all"} } });
</script>

<style type="text/css">
h1 { /* Header 1 */
 font-size: 24px;
}
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Growth
Growth is assumed to follow a re-parameterized von Bertalanffy function where the mean length at age $a$ ($L_a$) at the time of the survey is:
$$L_a = \tilde{L}_{a} \exp(-K \Delta_a) + L_{\infty}(1 - \exp(-K \Delta_a)),$$
where $\tilde{L}_{a}$ is the mean length of the cohort currently of age $a$ at the time of stocking, $L_{\infty}$ is the mean asymptotic length, $K$ is the von Bertalanffy growth coefficient, and $\Delta_a$ is the accumulated degree days (converted to years) experienced by the cohort of age $a$.

The variability in length-at-age $\sigma_a$ in the population is assumed to be normally distributed in the absence of fishing and proportional to $L_a$ by a coefficient of variation $CV$:
$$\sigma_a = CV \times L_a.$$
Thus, probability of a fish to be within a length bin of mid-point $\ell$ at age $a$ is
$$\textrm{P}(\ell|a) = \frac{1}{\sigma_a\sqrt{2\pi}}\int_{\ell-d}^{\ell+d}\exp\left(\frac{(L_a - x)^2}{2\sigma_a^2}\right)dx,$$
where $d$ is the half the width of the length bin.

# Population model
Selectivity $v$ of the anglers and the survey gillnet is assumed to be logistic and size-specific, parameterized as
$$v^{AN}_{\ell} = [1 + \exp(-\gamma^{AN}\{\ell - h^{AN}\})]^{-1} $$
and 
$$v^{GN}_{\ell} = [1 + \exp(-\gamma^{GN}\{\ell - h^{GN}\})]^{-1}, $$
where $\gamma$ is the slope of the logistic curve at 50% selectivity, $h$ is the length at 50% selectivity, and the superscript indexes type ($AN$ = angler and $GN$ = gillnet).

The population abundance of length $\ell$ and age $a$ is given by
$$N_{\ell,a} = R_{\ell,a}\exp(-\Sigma_{a'=1}^{a-1} [F_{\ell'(a')} + M]),$$
where $M$ is the instantaneous natural mortality rate,
$$R_{\ell,a} = N^{stock}_a \textrm{P}(\ell|a),$$
where $N^{stock}_a$ is the stocking density and $R_{\ell,a}$ would be the abundance of animals of length $\ell$ and age $a$ in the absence of mortality,
$$ F_{\ell'(a')} = v_{\ell'(a')}^{AN} F,$$
where $F$ is the apical instantaneous fishing mortality rate, and
$$\ell'(a') = \frac{\ell}{L_a}L_{a'}.$$

Equation 6 calculates the current abundance of the age-$a$ cohort as a function of cumulative fishing pressure from previous ages $a' = 1, \ldots, a-1$. Since selectivity is size-based, animals in a cohort may not experience equal magnitudes of fishing mortality over time. We assume larger animals in the cohort remain proportionally large (relative to $L_{a}$) for the entirety of the cohort's lifespan (and smaller animals remain proportionally small). The summation in Equation 6 accounts for this phenomenon when calculating historical fishing mortality. In other words, Equation 9 calculates a fish at current length $\ell$ had been length $\ell'$ at age $a'$, so that angler selectivity can be calculated accordingly in Equation 8.

# Iterative solution for F

Fishing mortality is influenced by direct harvest of fish, subject to total fishing effort, capture efficency, voluntary release, and regulations (e.g. bag limits). We assume $F$ also includes release mortality for fish returned to the water through voluntary or regulated release due to bag limits. 

From an estimate of effort $E$, catchability $q$, and the probability of harvest $p_h$, and release mortality $F_{release}$, fishing mortality is calculated as:
$$F = qE[p_h + (1 - p_h)F^{release}].$$
We usually don't have $p_h$ but rather the bag limit $b_{lim}$. To calculate $p_h$ from the bag limit $b_{lim}$, we first calculate the expected catch in length and age based on the Baranov equation and an initial value of $F$, 
$$ C_{\ell,a}= \frac{v^{AN}_{\ell} F}{v^{AN}_{\ell} F+M} N_{\ell,a} [1 - \exp(-v^{AN}_{\ell} F-M)] .$$
The expected $CPUE$ is
$$CPUE = \frac{\Sigma_{\ell}\Sigma_{a} C_{\ell, a}}{E}.$$
Next, the expected value of the CPUE (pertaining to retained catch) subject to the bag limit ($CPUE | b_{lim}$) is calculated. If the CPUE for individual anglers is a Poisson random variable with rate parameter $\lambda = CPUE$, then $CPUE|b_{lim}$ can be calculated as:
$$CPUE|b_{lim} = \Sigma_x g(x) f(x;\lambda) $$
where
$$ g(x) = \textrm{min}(x, b_{lim}),$$
and $f(x;\lambda)$ is the probability density function for a Poisson random variable,
$$ f(x;\lambda) = \exp(-\lambda) \frac{\lambda^x}{x!},$$
with $x = 0, 1, 2, \ldots$. Generally, the summation is stopped at some arbitrarily large number (e.g., 20).

Then, the probabilty of harvest $p_h$ is
$$p_h = \frac{CPUE|b_{lim}}{CPUE}.$$
From a starting value of $p_h$, $F$ is solved iteratively through Equations 10-16 until the value stabilizes (often at 5 iterations or fewer).


# Likelihood

In the model, the numbers at length and age from the survey $N^{GN}_{\ell,a}$ is calculated as
$$N^{GN}_{\ell,a} = v^{GN}_{\ell} N_{\ell,a},$$

Assuming a multinomial distribution, the log-likelihood ($\Lambda_1$) for a random sample of length-age observationss is
$$\Lambda_1 = O_{\ell,a} \log\left(\dfrac{N^{GN}_{\ell,a}}{\Sigma_{\ell}\Sigma_a N^{GN}_{\ell,a}}\right),$$
where $O$ is the observed numbers in the sample.

The observed numbers at length is calculated as:
$$N^{GN}_{\ell} = \Sigma_a N^{GN}_{\ell,a}.$$
The likelihood $\Lambda_2$ for a random sample of lengths is
$$\Lambda_2 = O_{\ell} \log\left(\dfrac{N^{GN}_{\ell}}{\Sigma_{\ell}N^{GN}_{\ell}}\right).$$

